### ISSUE TITLE
Unable to install cargo-binstall

### ISSUE THREAD

**Issue by nahsi** [moonrepo/setup-rust#10]
Trying to use the action on host where rustup is missing leads to this error:

```
Run moonrepo/setup-rust@v1
  with:
    inherit-toolchain: true
    cache-target: release
    cache: true
  env:
    RUSTFLAGS: -D warnings --cfg tokio_unstable
Setting cargo environment variables
Adding ~/.cargo/bin to PATH
Detecting toolchain
Loading rust-toolchain.toml or rust-toolchain file
Inheriting toolchain settings from inputs
Installing toolchain with rustup
/home/ubuntu/.cargo/bin/rustup toolchain install nightly-[2](https://github.com/fluencelabs/nox/actions/runs/5738400881/job/15551917509?pr=1741#step:3:2)02[3](https://github.com/fluencelabs/nox/actions/runs/5738400881/job/15551917509?pr=1741#step:3:3)-06-1[4](https://github.com/fluencelabs/nox/actions/runs/5738400881/job/15551917509?pr=1741#step:3:4) --profile minimal --target x86_64-unknown-linux-gnu --target aarch64-unknown-linux-gnu --component rustfmt --component clippy --no-self-update
info: syncing channel updates for 'nightly-2023-06-14-x86_64-unknown-linux-gnu'
info: latest update on 2023-06-14, rust version 1.72.0-nightly (371994e0d 2023-06-13)
info: component 'clippy' for target 'x86_64-unknown-linux-gnu' is up to date
info: component 'rust-std' for target 'aarch64-unknown-linux-gnu' is up to date
info: component 'rust-std' for target 'x86_64-unknown-linux-gnu' is up to date
info: component 'rustfmt' for target 'x86_64-unknown-linux-gnu' is up to date

  nightly-2023-06-14-x86_64-unknown-linux-gnu unchanged - rustc 1.72.0-nightly (371994e0d 2023-06-13)

/home/ubuntu/.cargo/bin/rustup default nightly-2023-06-14
info: using existing install for 'nightly-2023-06-14-x86_64-unknown-linux-gnu'
info: default toolchain set to 'nightly-2023-06-14-x86_64-unknown-linux-gnu'

  nightly-2023-06-14-x86_64-unknown-linux-gnu unchanged - rustc 1.72.0-nightly (371994e0d 2023-06-13)

info: note that the toolchain 'nightly-2023-06-14-x86_64-unknown-linux-gnu' is currently in use (overridden by '/opt/actions-runner/_work/nox/nox/rust-toolchain.toml')
Logging installed toolchain versions
/home/ubuntu/.cargo/bin/rustc +nightly-2023-06-14 --version --verbose
rustc 1.72.0-nightly (371994e0d 2023-06-13)
binary: rustc
commit-hash: 371994e0d8380600ddda78ca1be937c7fb179b49
commit-date: 2023-06-13
host: x86_64-unknown-linux-gnu
release: 1.72.0-nightly
LLVM version: 16.0.[5](https://github.com/fluencelabs/nox/actions/runs/5738400881/job/15551917509?pr=1741#step:3:5)
Installing additional binaries
cargo-binstall does not exist, attempting to install
Error: Cannot find module './133.index.js'
Require stack:
- /opt/actions-runner/_work/_actions/moonrepo/setup-rust/v1/dist/index.js
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module './133.index.js'
Require stack:
- /opt/actions-runner/_work/_actions/moonrepo/setup-rust/v1/dist/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.__nccwpck_require__.f.require (/opt/actions-runner/_work/_actions/moonrepo/setup-rust/v1/dist/index.js:[6](https://github.com/fluencelabs/nox/actions/runs/5738400881/job/15551917509?pr=1741#step:3:6)3801:28)
    at /opt/actions-runner/_work/_actions/moonrepo/setup-rust/v1/dist/index.js:63[7](https://github.com/fluencelabs/nox/actions/runs/5738400881/job/15551917509?pr=1741#step:3:7)36:40
    at Array.reduce (<anonymous>)
    at Function.__nccwpck_require__.e (/opt/actions-runner/_work/_actions/moonrepo/setup-rust/v1/dist/index.js:63735:67)
    at downloadAndInstallBinstall (/opt/actions-runner/_work/_actions/moonrepo/setup-rust/v1/dist/index.js:63077:5[8](https://github.com/fluencelabs/nox/actions/runs/5738400881/job/15551917509?pr=1741#step:3:9))
    at installBins (/opt/actions-runner/_work/_actions/moonrepo/setup-rust/v1/dist/index.js:63[12](https://github.com/fluencelabs/nox/actions/runs/5738400881/job/15551917509?pr=1741#step:3:13)2:[15](https://github.com/fluencelabs/nox/actions/runs/5738400881/job/15551917509?pr=1741#step:3:16)) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/actions-runner/_work/_actions/moonrepo/setup-rust/v1/dist/index.js'
  ]
}
```

**Comment by milesj** [comment]
@nahsi Ok should be good now.
